@startuml
!pragma layout smetana
hide circle
hide methods
skinparam classAttributeIconSize 0

object User
object Login
object profile
object Product
object Loan
object status
object reservation
object Return
object admin


Login --> Product
User --> Login
Login --> admin
Login --> profile
Product --> status
status <-- Loan
status <-- reservation
Product --> Return










@enduml