@startuml
!pragma layout smetana
class User{
  username
  email
  password
  name
}

class Student{
}

class Admin{
}

class Loan{
  loanDate
  dueDate
  returnDate
}

class Reservation{
  fromDate
  toDate
}

class Category{
  name
}

class Product{
  name
  description
  status
}

User <|-- Student
User <|-- Admin

Student "1" -- "0..*" Loan
Loan "0..*" -- "1" Product
Student "1" -- "0..*" Reservation
Reservation "0..*" -- "1" Product
Category "1" -- "0..*" Product

Admin "1" -- "0..*" Product : manages
@enduml