@startuml
!pragma layout smetana
class User{
  email
  password
}

class Student{
  name
  studentID
}

class Admin{
  name
}

class Loan{
  studentID
  studentName
  productID
  loanDate
  dueDate
  returnDate
  reservation
  history

}

class Category{
  name
  type
}

class Product{
  productName
  productID
  Description
  status

}

class History{
  productName
}

User <|-- Student
User <|-- Admin

Student "1" -- "0..*" Loan
Loan "0..*" -- "1" Product
Student "1" -- "0..*" Product


Admin "1" -- "0..*" Product : manages
@enduml